### ISSUE TITLE
trocar links que apontam para # para os lugares certo

### ISSUE THREAD

**Issue by santagada** [bikeanjo/landing#6]
peça e seja apontam para sistema.bikeanjo.com.br o resto tem que procurar

**Comment by nicolavieira** [comment]
Redes sociais

https://www.facebook.com/bikeanjo
https://plus.google.com/+bikeanjo/about
https://twitter.com/bikeanjo
https://www.youtube.com/channel/UCaFOaDBs3ixRF1wlTixKCZw
